### ISSUE TITLE
Using query-exporter as oracledb monitor  solution

### ISSUE THREAD

**Issue by xuanyuanaosheng** [albertodonato/query-exporter#101]
we using the  https://github.com/iamseth/oracledb_exporter as a solution to monitor our oracledb.  But I find some problem. So I change it to query-exporter.  The metircs is: https://github.com/iamseth/oracledb_exporter/blob/master/default-metrics.toml.

The yml file is:

```

databases:
  test_db:
    dsn: oracle+cx_oracle://DB_USER:XXXXXXX@(DESCRIPTION_LIST = (LOAD_BALANCE=OFF) (FAILOVER=ON) (DESCRIPTION = (CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3) (ADDRESS = (PROTOCOL = TCP)(HOST = TESTDBCN)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = TESTDBCN))) (DESCRIPTION = (CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3) (ADDRESS = (PROTOCOL = TCP)(HOST = DBTESTCN)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = TESTDBCN))))


metrics:
  oracledb_session_value:
    type: gauge
    description: Gauge metric with count of sessions by status and type.
    labels: [status, type]
  oracledb_resource_current_utilization:
    type: gauge
    description: Generic counter metric from v$resource_limit view in Oracle (current value).
    labels: [resource_name]
  oracledb_resource_limit_value:
    type: gauge
    description: "Generic counter metric from v$resource_limit view in Oracle (UNLIMITED: -1)."
    labels: [resource_name]
  oracledb_asm_diskgroup_total:
    type: gauge
    description: Total size of ASM disk group.
    labels: [name]
  oracledb_asm_diskgroup_free:
    type: gauge
    description: Free space available on ASM disk group.
    labels: [name]
  oracledb_activity_value:
    type: gauge
    description: Generic counter metric from v$sysstat view in Oracle.
    labels: [name]
  oracledb_process_count:
    type: gauge
    description: Gauge metric with count of processes.
  oracledb_wait_time_value:
    type: gauge
    description: Generic counter metric from v$waitclassmetric view in Oracle.
    labels: [wait_class]
  oracledb_tablespace_bytes:
    type: gauge
    description: Generic counter metric of tablespaces bytes in Oracle.
    labels: [tablespace, type]
  oracledb_tablespace_max_bytes:
    type: gauge
    description: Generic counter metric of tablespaces max bytes in Oracle.
    labels: [tablespace, type]
  oracledb_tablespace_free:
    type: gauge
    description: Generic counter metric of tablespaces free bytes in Oracle.
    labels: [tablespace, type]
  oracledb_slow_queries_p95_time_usecs:
    type: gauge
    description: "Gauge metric with percentile 95 of elapsed time."
  oracledb_slow_queries_p99_time_usecs:
    type: gauge
    description: "Gauge metric with percentile 99 of elapsed time."
  oracledb_big_queries_p95_rows:
    type: gauge
    description: "Gauge metric with percentile 95 of returned rows."
  oracledb_big_queries_p99_rows:
    type: gauge
    description: "Gauge metric with percentile 99 of returned rows." 
  oracledb_size_user_segments_top100_table_bytes:
    type: gauge
    description: "Gauge metric with the size of the tables in user segments."
    labels: [segment_name]
  oracledb_size_user_segments_top100_table_partition_bytes:
    type: gauge
    description: "Gauge metric with the size of the table partition in user segments."
    labels: [segment_name]
  oracledb_size_user_segments_top100_cluster_bytes:
    type: gauge
    description: "Gauge metric with the size of the cluster in user segments."
    labels: [segment_name]
  oracledb_dba_seg_top100_table_bytes:
    type: gauge
    description: "Gauge metric with the size of the tables in user segments."
    labels: [segment_name]
  oracledb_dba_seg_top100_table_partition_bytes:
    type: gauge
    description: "Gauge metric with the size of the table partition in user segments."
    labels: [segment_name]
  oracledb_dba_seg_top100_cluster_bytes:
    type: gauge
    description: "Gauge metric with the size of the cluster in user segments."
    labels: [segment_name]


queries:
  query1:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_session_value]
    sql: |
      SELECT status, type, COUNT(*) as oracledb_session_value FROM v$session GROUP BY status, type
  query2:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_resource_current_utilization, oracledb_resource_limit_value]
    sql: |
      SELECT resource_name,current_utilization as oracledb_resource_current_utilization,CASE WHEN TRIM(limit_value) LIKE 'UNLIMITED' THEN '-1' ELSE TRIM(limit_value) END as oracledb_resource_limit_value FROM v$resource_limit
  query3:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_asm_diskgroup_total, oracledb_asm_diskgroup_free]
    sql: |
      SELECT name,total_mb*1024*1024 as oracledb_asm_diskgroup_total,free_mb*1024*1024 as oracledb_asm_diskgroup_free FROM v$asm_diskgroup_stat where exists (select 1 from v$datafile where name like '+%')
  query4:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_activity_value]
    sql: |
      SELECT name, value as oracledb_activity_value FROM v$sysstat WHERE name IN ('parse count (total)', 'execute count', 'user commits', 'user rollbacks')
  query5:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_process_count]
    sql: |
      SELECT COUNT(*) as oracledb_process_count FROM v$process
  query6:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_wait_time_value]
    sql: |
      SELECT
        n.wait_class as WAIT_CLASS,
        round(m.time_waited/m.INTSIZE_CSEC,3) as oracledb_wait_time_value
        FROM
        v$waitclassmetric  m, v$system_wait_class n
        WHERE
          m.wait_class_id=n.wait_class_id AND n.wait_class != 'Idle'
  query7:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_tablespace_bytes, oracledb_tablespace_max_bytes, oracledb_tablespace_free]
    sql: |
      SELECT
          dt.tablespace_name as tablespace,
          dt.contents as type,
          dt.block_size * dtum.used_space as oracledb_tablespace_bytes,
          dt.block_size * dtum.tablespace_size as oracledb_tablespace_max_bytes,
          dt.block_size * (dtum.tablespace_size - dtum.used_space) as oracledb_tablespace_free
        FROM  dba_tablespace_usage_metrics dtum, dba_tablespaces dt
        WHERE dtum.tablespace_name = dt.tablespace_name
        ORDER by tablespace
  query8:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_slow_queries_p95_time_usecs, oracledb_slow_queries_p99_time_usecs]
    sql: |
      select  percentile_disc(0.95)  within group (order by elapsed_time) as oracledb_slow_queries_p95_time_usecs, percentile_disc(0.99)  within group (order by elapsed_time) as oracledb_slow_queries_p99_time_usecs from v$sql where last_active_time >= sysdate - 5/(24*60)
  query9:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_big_queries_p95_rows, oracledb_big_queries_p99_rows]
    sql: |
      select  percentile_disc(0.95)  within group (order by rownum) as oracledb_big_queries_p95_rows, percentile_disc(0.99)  within group (order by rownum) as oracledb_big_queries_p99_rows from v$sql where last_active_time >= sysdate - 5/(24*60)
  query10:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_size_user_segments_top100_table_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_size_user_segments_top100_table_bytes from user_segments where segment_type='TABLE' group by segment_name) order by oracledb_size_user_segments_top100_table_bytes DESC FETCH NEXT 100 ROWS ONLY
  query11:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_size_user_segments_top100_table_partition_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_size_user_segments_top100_table_partition_bytes from user_segments where segment_type='TABLE PARTITION' group by segment_name) order by oracledb_size_user_segments_top100_table_partition_bytes DESC FETCH NEXT 100 ROWS ONLY
  query12:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_size_user_segments_top100_cluster_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_size_user_segments_top100_cluster_bytes from user_segments where segment_type='CLUSTER' group by segment_name) order by oracledb_size_user_segments_top100_cluster_bytes DESC FETCH NEXT 100 ROWS ONLY
  query13:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_dba_seg_top100_table_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_dba_seg_top100_table_bytes from dba_segments where segment_type='TABLE' group by segment_name) order by oracledb_dba_seg_top100_table_bytes DESC FETCH NEXT 100 ROWS ONLY
  query14:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_dba_seg_top100_table_partition_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_dba_seg_top100_table_partition_bytes from dba_segments where segment_type='TABLE PARTITION' group by segment_name) order by oracledb_dba_seg_top100_table_partition_bytes DESC FETCH NEXT 100 ROWS ONLY
  query15:
    interval: 120
    databases: [cur_db]
    metrics: [oracledb_dba_seg_top100_cluster_bytes]
    sql: |
      select * from (select segment_name,sum(bytes) as oracledb_dba_seg_top100_cluster_bytes from dba_segments where segment_type='CLUSTER' group by segment_name) order by oracledb_dba_seg_top100_cluster_bytes DESC FETCH NEXT 100 ROWS ONLY


```

Welcome to update the metrics.
