### ISSUE TITLE
Can passwords be used from a Vault

### ISSUE THREAD

**Issue by mcarol44** [albertodonato/query-exporter#109]
Can we remove the passwords from the config file and pull them from our Vault?

Has anyone done this yet?

We are getting flagged for having passwords in plain text.

**Comment by free31307468** [comment]
Yes, you can refer the password from environment variable.
```yml
env: 
- name: password 
  valueFrom:
    serectKeyRef: my-secret
      name: password
      key: my-passowrd
- name: connection-string
  value: "oracle://account:$(password)@host/sid"
```
```yml
databases:
  my-database:
    dsn: 'env: connection-string'
```
