### ISSUE TITLE
Could not use the schema.table format in lable 

### ISSUE THREAD

**Issue by dkhomdo** [albertodonato/query-exporter#130]
Hi,
I'm using query exporter to collect metrics from Postgres version 13.5 and could not use the definition for label as: schema.table (ex: f1.receiver_customer). If not having this definition, Postgres will return: "column reference "receiver_customer" is ambiguous" and my query could not work accordingly.

The return error in query-exporter is: Invalid config at metrics/rate_count/labels/0: 'f1.receiver_customer' does not match '^[a-zA-Z_][a-zA-Z0-9_]*$'

Hereunder is my config and query:
```
   metrics:
      rate_count:
        type: gauge
        description: txn rate     
        labels: [f1.receiver_inst]      
  queries:
      query1:
        interval: 60
        databases: [db]
        metrics: [rate_count]
        sql: |
          SELECT f1.receiver_customer, f1.failed::decimal/f2.total as rate_count 
            FROM (select receiver_customer, count(1) as failed from po.ordering where status <> 'COMPLETED' and remark <> 'AUTH' and (date_time > current_timestamp - interval '3 days') group by receiver_customer) f1
            JOIN (select receiver_customer, count(1) as total from po.ordering where (date_time > current_timestamp - interval '3 days') group by receiver_customer having count(1) > 0) f2 
            ON f1.receiver_customer = f2.receiver_customer
```

Please help to analyze and advise
