### ISSUE TITLE
Metric doesn't reset to 0 value

### ISSUE THREAD

**Issue by NikChnv** [albertodonato/query-exporter#137]
**Describe the bug**

Metrics based on PostreSQL query doesn't reset when the query stops returning any value. For example if a query with a group clause returns 2 rows there would be 2 metrics. But if the same query would start to return one row there would still be 2 metrics.

**Installation details**

- query-exporter installation type:
  - docker image: query-exporter:2.8.3

**To Reproduce**

1. Create metrics from query that returns 2 rows
2. Modify database so that the query will return 1 row
3. Exporter still shows 2 metrics

**Comment by NikChnv** [comment]
slightly redacted config for the sake of not disclosing some info.
```
databases:
    database:
      dsn: env:POSTGRES_DSN

  metrics:
    status_count:
      type: gauge
      description: Amount of clusters by status
      labels: [status]

  queries:
    cluster_status:
      interval: 30
      databases: [database]
      metrics: [status_count]
      sql: >
        SELECT status, count(*) as status_count
          FROM public.tenant
          GROUP BY STATUS
```
