### ISSUE TITLE
How to injest database table data to prometheus

### ISSUE THREAD

**Issue by anurag-appperfect** [albertodonato/query-exporter#150]
I want to injest database query results to prometheus. I am executing a query and getting the result in table
![Screenshot 2023-05-23 at 4 50 09 PM](https://github.com/albertodonato/query-exporter/assets/94513745/b6dd3b27-c061-4e90-9e0b-ce292c7dba7d)
11 rows in set (0.006 sec)`

How to insert this data to prometheus using Prometheus

**Comment by albertodonato** [comment]
You can define a metric named `metric9` and use `name` as a label. It depends on what you need to do.

**Comment by anurag-appperfect** [comment]
Thank you for your suggestion and do I need to pass separate parameters for each value of name ?

**Comment by albertodonato** [comment]
it depends on your query

**Comment by anurag-appperfect** [comment]
```
 query8:
     interval: 5
     databases: [db1]
     metrics: [metric8]
     sql: select count(*) AS metric8, :param AS study from study_db WHERE type_study = :param group by study_db order by COUNT(*) desc;
     parameters:
       - param: "OP"
       - param: "OT"
       - param: "XC"
       - param: "OPT"
       - param: "OP\\OPT"
       - param: "XC\\OPT"
       - param: "XC\\OT"
       - param: " "
       - param: "SC"
       - param: "XC\\OT\\OP"
       - param: "OT\\OP"
```

Here is the code sample, what should I do to avoid passing each value of param ?
