### ISSUE TITLE
query "query2" on database "db2" failed: Wrong column names from query

### ISSUE THREAD

**Issue by connorourke** [albertodonato/query-exporter#156]
**Describe the bug**

I am testing using query-exporter but when executing a query I get:

` query-exporter - query "query2" on database "db2" failed: Wrong column names from query`

**Installation details**

- operating system: 
```
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```
- query-exporter installation type:
pip install query-exporter
query-exporter 2.8.3

**To Reproduce**

I am using the folloiwing config file:

```
databases:
   db1:
     dsn: sqlite:////test.db
     connect-sql:
       - PRAGMA application_id = 123
       - PRAGMA auto_vacuum = 1
     labels:
        region: us1
        app: app1
   db2:
     dsn: sqlite:////data.db
     connect-sql:
       - PRAGMA application_id = 123
       - PRAGMA auto_vacuum = 1
     labels:
        region: us1
        app: app2

metrics:
  metric1:
    type: gauge
    description: A sample gauge
  award_metric:
    type: gauge
    description: Award amount


queries:
  query1:
    interval: 5
    databases: [db1]
    metrics: [metric1]
    sql: SELECT random() / 1000000000000000 AS metric1
  query2:
    interval: 5
    databases: [db2]
    metrics: [award_metric]
    sql: SELECT sum(amount) from awards AS award_metric
```

I can connect to the data.db and run the query `SELECT sum(amount) from awards AS award_metric` fine with sqlite3.

Any idea why I am getting this error?
