### ISSUE TITLE
Invalid config at queries/sql: 'SELECT count("id") as metric1 FROM rss' is not of type 'object'

### ISSUE THREAD

**Issue by BoKKeR** [albertodonato/query-exporter#157]
**Describe the bug**

A clear and concise description of what the bug is and when it happens.

**Installation details**

- operating system: [OS and version]: portainer
- query-exporter installation type:
  - docker image:  latest

**To Reproduce**

I am just a SQL newbie trying to setup my first metric, a simple gauge count based on how many entries there are in the table. The error I get is 

`Invalid config at queries/sql: 'SELECT count("id") as metric1 FROM rss' is not of type 'object'`

1. Config file content (redacted of secrets if needed)

```
metrics:
  metric1:
    type: gauge
    description: A sample gauge
  metric2:
    type: summary
    description: A sample summary
    labels: [l1, l2]
    expiration: 24h
  metric3:
    type: histogram
    description: A sample histogram
    buckets: [10, 20, 50, 100, 1000]

queries:
  query1:
    interval: 5
    databases: [db1]
    metrics: [metric1]
  sql: SELECT count("id") as metric1 FROM rss
~
~
```

2. Ran query-exporter with the following command line ...
ran it from docker
3. Got the error when ...
checking logs
