### ISSUE TITLE
Add option to change config file path

### ISSUE THREAD

**Issue by BoKKeR** [albertodonato/query-exporter#158]
**Is your feature request related to a problem? Please describe.**
Currently to my knowledge there is no way to mount a file from a named volume with docker-compose. 

```
---
version: "3"
services:      
  sqlite_exporter:
    image: adonato/query-exporter:latest
    volumes: 
      - "rss_sqlite_exporter/config.yaml:/config.yaml"

volumes:
  rss_sqlite_exporter:
    external: true

```

```
Failure
Ignoring unsupported options: restart service sqlite_exporter: undefined volume "rss_sqlite_exporter/config.yaml"
```

**Describe the solution you'd like**
I would prefer to be able to change the config file location, this way I could move it to a folder and mount the named volume as a folder. The path could be set with an env variable as `-e CONFIG_PATH="/config/config.yaml"`

**Describe alternatives you've considered**
Mounting the file from the node-s filesystem works perfectly fine, but its NOT a great solution since named volumes are meant to prevent us from polluting the nodes filesystem.

```
    volumes: 
      - "/tmp/config.yaml:/config.yaml"
```
