### ISSUE TITLE
Exclude `database` label at exporter level

### ISSUE THREAD

**Issue by robbat2** [albertodonato/query-exporter#173]
**Is your feature request related to a problem? Please describe.**
I want to avoid exporting a meaningless label for database.

Present state
```
mymetric{database="db",label1="value1"} NNNN
```

**Describe the solution you'd like**
Require users to explicitly declare the `database` label in the config.

Desired state:
```
mymetric{label1="value1"} NNNN
```

**Describe alternatives you've considered**
label drop in Prometheus/Mimir/VictoriaMetrics is possible, but has to be configured on every scraper.

**Additional context**
The present design implicitly breaks anybody who ever wanted their own label of `database`.

**Comment by robbat2** [comment]
In the README sample configuration and output, there's this example:
```
queries_total{app="app1",database="db1",query="query1",region="us1",status="success"} 50.0
```
The `database` label is NOT declared in the `labels` section of the config, and there's no direct way in the config to remove it.

For users that want it to persist, I'd tell them to explicitly configure it in `labels`, e.g.:
```
databases:
  db1:
    dsn: sqlite://
    connect-sql:
      - PRAGMA application_id = 123
      - PRAGMA auto_vacuum = 1
    labels:
      region: us1
      app: app1
      database: db1 # this line is new
```

If you were worried about breaking existing configs, maybe accept the label value being empty as a sign to remove it:
```
databases:
  db1:
    dsn: sqlite://
    connect-sql:
      - PRAGMA application_id = 123
      - PRAGMA auto_vacuum = 1
    labels:
      region: us1
      app: app1
      database: # new line, empty value => remove the label in the output metric
```

Expected result:
```
queries_total{app="app1",query="query1",region="us1",status="success"} 50.0
```
