### ISSUE TITLE
Invalid config at queries

### ISSUE THREAD

**Issue by kuntsali** [albertodonato/query-exporter#175]
**Describe the bug**

Not sure if this a bug, but. I'm trying to configure metric for replication slot status. But I'm getting error during runtime:
`Invalid config at queries/pg_replication_slots_active: Additional properties are not allowed ('database' was unexpected)`

**Installation details**

- query-exporter installation type:
  - docker image: [`2.8.3`]

**Config**
```
metrics:
    pg_replication_slots_active:
      labels: [slot_name, database_name]
      type: gauge
      description: Replication slot status
      expiration: 60s

queries:
    pg_replication_slots_active:
      database: db
      metrics: [pg_replication_slots_active]
      interval: 30s
      sql: |
        SELECT active::int as pg_replication_slots_active, slot_name, database AS database_name FROM pg_replication_slots;
```
Obviously that there is a problem with config, but I can't figure out it on my own 😞 
Thanks in advance.
