### ISSUE TITLE
Metric name length

### ISSUE THREAD

**Issue by ygueguindecath** [albertodonato/query-exporter#183]
**Describe the bug**

Hi, we use query exporer for a lot of metrics, but one configuration make us struggler and i do not know why.

We have a definition of metric like this 

```yaml
xxx_1d:
  type: counter
  description: xxx
  increment: false
```

```yaml
xxx_1d:
  databases: [xxx]
  metrics:
    - xxx_1d
  sql: >
    select count(1) as xxx_1d from xxx;
  interval: 24h
```
        
But at the start we got an error saying it search for metric xxx_1.
I suspect a metric name length restriction as, this occur only for this query, and it's the only one that the name is more than 64 characters, but i'm not sure at all
        
**Installation details**

- operating system: kubernetes 1.27 ( GCP )
- query-exporter installation type:
  - docker image: 2.9.0

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)

```yaml
metrics:
    xxxxxxxx_xxxxxx_xxxxxxx_xxxxx_xxxxxxx_xxxxxxxxx_xxxxxxxxxxxxx_1d:
      type: counter
      description: desc
      increment: false
queries:
  xxxxxxxx_xxxxxx_xxxxxxx_xxxxx_xxxxxxx_xxxxxxxxx_xxxxxxxxxxxxx_1d:
    databases: [database]
    metrics:
      - xxxxxxxx_xxxxxx_xxxxxxx_xxxxx_xxxxxxx_xxxxxxxxx_xxxxxxxxxxxxx_1d
    sql: >
      select count(1) as xxxxxxxx_xxxxxx_xxxxxxx_xxxxx_xxxxxxx_xxxxxxxxx_xxxxxxxxxxxxx_1d from database.table;
    interval: 24h
 ```
      
2. Ran query-exporter with the following command line ...
 run the docker image with final cmd 
 `query-exporter /config.yaml -H 0.0.0.0`
3. Got the error when ...
Running the query first
