### ISSUE TITLE
query_exporter still supplying metric for db row that no longer exists

### ISSUE THREAD

**Issue by lchopfpt** [albertodonato/query-exporter#206]
**Describe the bug**

Using a query that does something like: `select time, task from table `
which collects multiple rows from that table.  When one of the rows is removed from the database, query_exporter seems to continue to supply a metric for the row with its last value even though the row no longer exists. 

**Installation details**

- operating system: Alma 9.2
- query-exporter installation type:
  - docker image: query-exporter:2.10.0

**To Reproduce**

1. mysql database, with simple schema of timestamp, and varchar.  
```
 CREATE TABLE task_state (
  task varchar(48) NOT NULL,
  last_ts datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (task),
  KEY last_ts_idx (last_ts)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 
```
Add a couple of rows.  

Configure and run query_exporter:
query_exporter metric:

```
task_state_last_ts:
    type: gauge
    description: A gauge based on tast_state last_ts
    labels:
    - task
```

query_exporter query: 
 ```
 task_state_ts:
    interval: 5m
    databases: [db]
    metrics: [task_state_last_ts]
    sql: select 'task_state_ts' as query, unix_timestamp(last_ts) as task_state_last_ts, task from task_state 
```

As query_exporter runs, it will pull in a metric for each row in the task_state table.  Update the dates in the database table to be current and let query_exporter pull it.  
Then remove one of the rows from the table.
(Delete from task_state where task='foo')
After next query, query_exporter is still producing a metric for that removed task.  The task_state_ts value does get old as its static to it's last correct pull.
