### ISSUE TITLE
Issue in adding new unsupported database

### ISSUE THREAD

**Issue by mateocolina** [albertodonato/query-exporter#231]
**Describe the bug**

I'm currently trying to setup Query-Exporter with Teradata. I'm running query-exporter in Docker and have manually patched and built the image to install the SQLAlchemy library for Teradata (teradatasqlalchemy). After setting up the DSN name it fails, the same connection string works when connecting directly with SQLAlchemy, but not through the config.yaml. I tried both DSN as string (quoted username, password and options) and as a map (see config.yaml below), both didn't work.

Following error message gets thrown: `Invalid database DSN: "teradatasql://<quoted_username>:<quoted_password>@host.docker.internal"`

Funnily, I can't enable a more verbose message output. Parameter `query-exporter -L DEBUG /config/config.yaml` has no impact.

**Installation details**

- operating system: [OS and version]
- query-exporter installation type:
  - pip: [output from `pip list`]
  - docker image: 3.11.1
  - snap: [output from `snap info query-exporter`]

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)
```
# config.yaml
---
databases:
  sdw:
    #dsn: "teradatasql://<quoted_username>:<quoted_password>@host.docker.internal:1025"
    dsn:
      dialect: "teradatasql"
      user: "<quoted_username>"
      password: "<quoted_password>"
      host: "host.docker.internal"
      port: 1025

metrics:
  num_of_errors:
    type: gauge
    description: Number of errors

queries:
  query_num_of_errors:
    interval: 5
    databases: [sdw]
    metrics: [num_of_errors]
    sql: |
      select random(1, 10) as num_of_errors
```
2. Ran query-exporter with the following command line ...
`query-exporter -H 0.0.0.0 /config/config.yaml`

3. Got the error when ...
Starting the docker container
