### ISSUE TITLE
Add support for static label for DB

### ISSUE THREAD

**Issue by Teriand** [albertodonato/query-exporter#27]
**Is your feature request related to a problem? Please describe.**
ex.
have oracle server with 4 instance: uz1/uz2/uz3/uz4
simple metric up:
```
queries:
  query1:
    interval: 10
    databases: [uz1, uz2,, uz3,, uz4]
    metrics: [up]
    sql: select 1 as up from dual
```
and generated metric:
```
up{database="uz1"} 1.0
up{database="uz2"} 1.0
up{database="uz3"} 1.0
up{database="uz4"} 1.0
```
But i need combine databases with one label server/stand/zone, etc
like:
```
up{database="uz1",server="1.2.3.4"} 1.0
up{database="uz2",server="1.2.3.4"} 1.0
up{database="uz3",server="1.2.3.4"} 1.0
up{database="uz4",server="1.2.3.4"} 1.0
```
yes it canbe resolved by 
```
sql: select '1.2.3.4' as server, 1 as up from dual
```
but when add new database in list with other server ip need add new metric

**Describe the solution you'd like**
Add static_label + static_value for databases config.
```
databases:
  uz1:
    dsn: oracle+cx_oracle://
    static_label: server
    static_value: 1.2.3.4
  uz2:
    dsn: oracle://
    static_label: server
    static_value: 4.3.2.1
```

**Describe alternatives you've considered**
Or crazy but flexible variant:
```
queries:
  query1:
    interval: 10
    databases: [uz1, uz2,, uz3,, uz4, uz_other]
    metrics: [up]
    sql: select :param as server, 1 as up from dual
    parameters:
       - param1: 1.2.3.4
             databases_to_send: [uz1, uz2,, uz3,, uz4]
       - param1: 4.3.2.1
              databases_to_send: [uz_other]
```
with new key  to separate send param1 with list db.

**Comment by albertodonato** [comment]
Hi, could you please explain the use case for adding these labels?

In your first solution, it seems you could just use the `database` label to distinguish them, while I don't understand exactly the reason for second solution.
If you're trying to group series across a subset of `database` values, you should be able to do so with a Prometheus query.

Also, Prometheus supports [relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) which might be useful in this case.

**Comment by Teriand** [comment]
database label cant group simple need other label for grouping
ex. for current working set with prom-sql/sql-agent (i need migrate to query-exporter)
```
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="foris611",stand="ru-6.11",zone="integration"} | 1
-- | --
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="foris612",stand="ru-6.12",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="frsru67",stand="msk-ru67",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="ua1",stand="ua1",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzbill",stand="uz-dev",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzbill63",stand="uz-test63",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzcrm",stand="uz-dev",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzcrm63",stand="uz-test63",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzfsys",stand="uz-dev",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzfsys63",stand="uz-test63",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzumrs",stand="uz-dev",zone="integration"} | 1
query_result_up{instance="prometheus-01:8080",job="ora",ora_instance="uzumrs63",stand="uz-test63",zone="integration"}
```

ora_instance = database
other labels are used to group on a dashboard/alerts


relabel cant add different label with one job

ex. One jon for all database with 1 static label for ZONE
```
  - job_name: 'ora'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus-01:9560']
        labels:
          zone: integration
```
I cant add new job for new server db.

**Comment by albertodonato** [comment]
Ok, I think something like this could work:

```
databases:
  uz1:
    dsn: oracle://
    labels:
      server: 1.2.3.4
      instance: foo
  uz2:
    dsn: oracle://
    labels:
      server: 4.3.2.1
      instance: bar
```

where declared labels (`server`, `instance`) would get added to all metrics (as the automatic `database` one), with the actual value for each database.

The only caveat would be that when using static labels, all databases need to have the same set, so that they can get applied to all metrics. While technically possible to have different label names if queries update different metrics from different databases, it probably gets confusing, so I'd like to avoid that.

I'll take a look at implementing this option.
