### ISSUE TITLE
Query Exporter stops working after short while

### ISSUE THREAD

**Issue by adduc** [albertodonato/query-exporter#28]
**Describe the bug**
I am in the process of evaluating query exporter. Using the docker image `adonato/query-exporter:2.1.0`, after approximately six minutes requests to the service start timing out.

Running with `-L DEBUG`, I receive the following error when the service starts to time out:
> query-exporter_1  | 2020-03-02 18:40:58,936 - ERROR - query-exporter - error from database "slave": QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)

On the database server, I can see 30 sleeping connections opened from the service:

<details>
  <summary>MySQL Process List</summary>

```
+--------+--------------+---------------------+----------+-----------+------+-----------------------------------------------------------------------------+------------------+----------+
| Id     | User         | Host                | db       | Command   | Time | State                                                                       | Info             | Progress |
+--------+--------------+---------------------+----------+-----------+------+-----------------------------------------------------------------------------+------------------+----------+
| 113949 | databaseuser | 192.168.10.54:46486 | database | Sleep     | 1491 |                                                                             | NULL             |    0.000 |
| 113953 | databaseuser | 192.168.10.54:46532 | database | Sleep     | 1466 |                                                                             | NULL             |    0.000 |
| 113955 | databaseuser | 192.168.10.54:46536 | database | Sleep     | 1451 |                                                                             | NULL             |    0.000 |
| 113960 | databaseuser | 192.168.10.54:46554 | database | Sleep     | 1446 |                                                                             | NULL             |    0.000 |
| 113963 | databaseuser | 192.168.10.54:46556 | database | Sleep     | 1421 |                                                                             | NULL             |    0.000 |
| 113964 | databaseuser | 192.168.10.54:46564 | database | Sleep     | 1391 |                                                                             | NULL             |    0.000 |
| 113969 | databaseuser | 192.168.10.54:46602 | database | Sleep     | 1376 |                                                                             | NULL             |    0.000 |
| 113974 | databaseuser | 192.168.10.54:46618 | database | Sleep     | 1361 |                                                                             | NULL             |    0.000 |
| 113977 | databaseuser | 192.168.10.54:46636 | database | Sleep     | 1346 |                                                                             | NULL             |    0.000 |
| 113980 | databaseuser | 192.168.10.54:46640 | database | Sleep     | 1331 |                                                                             | NULL             |    0.000 |
| 113983 | databaseuser | 192.168.10.54:46644 | database | Sleep     | 1316 |                                                                             | NULL             |    0.000 |
| 113986 | databaseuser | 192.168.10.54:46650 | database | Sleep     | 1286 |                                                                             | NULL             |    0.000 |
| 113989 | databaseuser | 192.168.10.54:46662 | database | Sleep     | 1271 |                                                                             | NULL             |    0.000 |
| 113994 | databaseuser | 192.168.10.54:46764 | database | Sleep     | 1256 |                                                                             | NULL             |    0.000 |
| 113997 | databaseuser | 192.168.10.54:46776 | database | Sleep     | 1240 |                                                                             | NULL             |    0.000 |
| 114056 | databaseuser | 192.168.10.54:47192 | database | Sleep     |  811 |                                                                             | NULL             |    0.000 |
| 114059 | databaseuser | 192.168.10.54:47210 | database | Sleep     |  791 |                                                                             | NULL             |    0.000 |
| 114060 | databaseuser | 192.168.10.54:47226 | database | Sleep     |  761 |                                                                             | NULL             |    0.000 |
| 114065 | databaseuser | 192.168.10.54:47256 | database | Sleep     |  741 |                                                                             | NULL             |    0.000 |
| 114070 | databaseuser | 192.168.10.54:47282 | database | Sleep     |  733 |                                                                             | NULL             |    0.000 |
| 114073 | databaseuser | 192.168.10.54:47288 | database | Sleep     |  732 |                                                                             | NULL             |    0.000 |
| 114074 | databaseuser | 192.168.10.54:47292 | database | Sleep     |  731 |                                                                             | NULL             |    0.000 |
| 114075 | databaseuser | 192.168.10.54:47296 | database | Sleep     |  726 |                                                                             | NULL             |    0.000 |
| 114076 | databaseuser | 192.168.10.54:47298 | database | Sleep     |  725 |                                                                             | NULL             |    0.000 |
| 114079 | databaseuser | 192.168.10.54:47300 | database | Sleep     |  721 |                                                                             | NULL             |    0.000 |
| 114080 | databaseuser | 192.168.10.54:47302 | database | Sleep     |  716 |                                                                             | NULL             |    0.000 |
| 114081 | databaseuser | 192.168.10.54:47304 | database | Sleep     |  686 |                                                                             | NULL             |    0.000 |
| 114084 | databaseuser | 192.168.10.54:47308 | database | Sleep     |  671 |                                                                             | NULL             |    0.000 |
| 114089 | databaseuser | 192.168.10.54:47320 | database | Sleep     |  641 |                                                                             | NULL             |    0.000 |
| 114092 | databaseuser | 192.168.10.54:47330 | database | Sleep     |  625 |                                                                             | NULL             |    0.000 |
```
</details>

**Installation details**
- operating system: ubuntu:19.10
- query-exporter installation type:
  - [x] docker image: 2.1.0

**To Reproduce**

<details>
  <summary>docker-compose.yml</summary>

```yml

  query-exporter:
    image: adonato/query-exporter:2.1.0
    mem_limit: 64M
    volumes:
    - ./config/query-exporter/config.yml:/config.yml
    command:
    - "-L"
    - "DEBUG"
    - "--process-stats"
    - "/config.yml"
    ports:
    - "$GATEWAY_IP:9560:9560"
    environment:
      DB_DSN: $DB_DSN
```
</details>

<details>
  <summary>config.yml</summary>

```yml
databases:
  slave:
    dsn: env:DB_DSN
    keep-connected: false

metrics:
  transaction_declines:
    type: gauge
  transaction_sales:
    type: gauge

queries:
  transaction_declines:
    interval: null
    databases: [slave]
    metrics: [transaction_declines]
    sql: |
      -- Quick query that takes <0.1ms to run
      [REDACTED]

  transaction_sales:
    interval: null
    databases: [slave]
    metrics: [transaction_sales]
    sql: |
      -- Quick query that takes <0.1ms to run
      [REDACTED]
```
</details>
