### ISSUE TITLE
Multiple Queries

### ISSUE THREAD

**Issue by brunowego** [albertodonato/query-exporter#31]
I'm trying run a SQL with multiple queries, like a script: 

```yaml
databases:
    xxx:
      dsn: env:DB2_DATABASE_DSN

  metrics:
    xxx_last_max_data:
      type: counter
      description: A counter

  queries:
    last_max_data:
      interval: 5
      databases: [xxx]
      metrics: [xxx_last_max_data]
      sql: |
        SET CURRENT QUERY ACCELERATION = NONE;
        SELECT
            MAX(ACTION) AS xxx_last_max_data
        FROM
            XXX.XXX
        WHERE
            ACTION BETWEEN xxx
            and yyy;
```

What you think about another optional (true/false) parameter that allow script execution?

**Comment by albertodonato** [comment]
Supporting multiple queries is technically possible, but seems a bit too specific to this use case, since only the last query in the sequence would be the one that actually returns metrics data.

I'm not familiar with DB2, is the `QUERY ACCELERATION` setting per connection or per transaction? I'm wondering if supporting running a set of queries at connection would be useful.

**Comment by brunowego** [comment]
Thanks @albertodonato to the quick reply. So, I'm not a expert in Db2 to, but I think this is per connection, because after set it, every transaction will use this.

Yes! A option to set it in database connection will be great!

**Comment by brunowego** [comment]
Another case that I need run a SET query before.

```sql
SET time_zone = 'UTC';
SELECT
    COUNT(1)
FROM
    matomo_log_link_visit_action
WHERE
    server_time > DATE_SUB(NOW(), INTERVAL 1 MINUTE);
```

**Comment by albertodonato** [comment]
As a workaround, is there any way to define a function that calls the `SET` and returns the result from the `SELECT`, and set `sql: SELECT * FROM somefunction()` ?

**Comment by brunowego** [comment]
@albertodonato this is a alternative. But, in my case, my user no have create access, only read.

**Comment by albertodonato** [comment]
I have a tentative solution (adding support for queries to run at connection) here: https://github.com/albertodonato/query-exporter/tree/connection-queries

You can 
```yaml
databases:
  db:
    dsn: env:DB2_DATABASE_DSN
    connect-sql:
      - SET time_zone = 'UTC'
      - SET CURRENT QUERY ACCELERATION = NONE
```

Could you please test it with your setup?

It'll need some more work before merging but it'd be good to know if it solves the use case properly.
