### ISSUE TITLE
Multiple set of parameters

### ISSUE THREAD

**Issue by brunowego** [albertodonato/query-exporter#32]
I'm lost about use of parameters. I may not have understood, but shouldn't each set of parameters generate a different metric?
 
```yml
databases:
  xxx:
    dsn: env:DB2_DATABASE_DSN
    connect-sql:
      - SET CURRENT QUERY ACCELERATION = NONE

  xxx_acc:
    dsn: env:DB2_DATABASE_DSN
    connect-sql:
      - SET CURRENT QUERY ACCELERATION = ALL

metrics:
  xxx_xxx_max:
    type: gauge
    description: A gauge

queries:
  xxx_xxx_max:
    interval: 5
    databases: [xxx, xxx_acc]
    metrics: [xxx_xxx_max]
    parameters:
      - min: 1001
        max: 2000
      - min: 2001
        max: 3000
      - min: 3001
        max: 4000
    sql: |
      SELECT
          MAX(XXX) AS xxx_xxx_max
      FROM
          XXX.XXX
      WHERE
          XXX BETWEEN :min
          and :max;
```

Thanks!

**Comment by albertodonato** [comment]
Not necessarily. Parameters cause the query to be executed once for each set, updating the metric multiple times.
In your example, since the metric is a gauge, you will only see the last value, though.
You can have different series for the same metric by adding a label, though.

Something like:

```yaml
databases:
  xxx:
    dsn: env:DB2_DATABASE_DSN
    connect-sql:
      - SET CURRENT QUERY ACCELERATION = NONE

  xxx_acc:
    dsn: env:DB2_DATABASE_DSN
    connect-sql:
      - SET CURRENT QUERY ACCELERATION = ALL

metrics:
  xxx_xxx_max:
    type: gauge
    description: A gauge
    labels: [somelabel]

queries:
  xxx_xxx_max:
    interval: 5
    databases: [xxx, xxx_acc]
    metrics: [xxx_xxx_max]
    parameters:
      - min: 1001
        max: 2000
        somelabel: foo
      - min: 2001
        max: 3000
        somelabel: bar
      - min: 3001
        max: 4000
        samelabel: baz
    sql: |
      SELECT
          MAX(XXX) AS xxx_xxx_max,
          :somelabel AS somelabel
      FROM
          XXX.XXX
      WHERE
          XXX BETWEEN :min
          and :max
```

I'm not sure about your usecase, but you could also consider using a histogram metric, with buckets to match the ranges you're passing in parametres.
