### ISSUE TITLE
ibm_db not usable in Docker

### ISSUE THREAD

**Issue by albertodonato** [albertodonato/query-exporter#40]
> The dns for db2 should be `db2+ibm_db://...`.
> Can you try if that works for you?

That doesn't work either, i am sorry... i tried the following:
```
db2+ibm_db_sa://<user>:<pass>@<ip>:<port>/<database>;
ibm_db://<user>:<pass>@<ip>:<port>/<database>;
```
these two give an "Invalid database DSN"
```
ibm_db_sa://<user>:<pass>@<ip>:<port>/<database>;
db2+ibm_db://<user>:<pass>@<ip>:<port>/<database>;
```
these two give an "module "ibm_db" not found"

The rest of the testing configuration is pretty much forward:
```
databases:
  c03:
    dsn: <...>

metrics:
  metric1:
    type: gauge
    description: test

queries:
  query1:
    interval: 5
    databases: [c03]
    metrics: [metric1]
    sql: SELECT RAND() as metric1 FROM SYSIBM.SYSDUMMY1

```
> I'll push the fix for the Dockerfile in the next release soon.

Thanks :)

_Originally posted by @Docjones in https://github.com/albertodonato/query-exporter/pull/39#issuecomment-625067999_
