### ISSUE TITLE
Docker + MSSQL how to specify the connection string

### ISSUE THREAD

**Issue by jonnisell** [albertodonato/query-exporter#42]
I'm trying to connect to a local MSSQL-docker using the Docker image of query-exporter ( in a docker-compose env) with various connection strings, but no one works.

**Installation details**
  - docker image: adonato/query-exporter:latest
  - SQL Server image [official MSSQL image](mcr.microsoft.com/mssql/server:2017-latest)

Installation through running  `pipenv shell` -> `pip3 install .` -> `query-exporter config.yaml` works fine, so I can get metrics working when installed on local system ✅ 

**To Reproduce**
* Prerequisite: MS SQL server running, exposing port 1433

1. Config file content
```yaml
databases:
  db1:
    dsn: mssql+pyodbc://<username>:<password>@localhost:1433/master
    labels:
      region: us1
      app: app1
```
  sections [metrics] and [queries] unaltered from your example

2. Ran query-exporter with the following 
`docker run -p 9560:9560/tcp -v "$PWD/config.yaml:/config.yaml" --rm -it \
    adonato/query-exporter:latest -- /config.yaml`

3. Error log: 
> query-exporter - error from database "db1": (pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
