### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by stephenfrench9** [albertodonato/query-exporter#44]
I am attempting to use query-exporter. 

here is my config file:

```
databases:
  db1:
    dsn: postgresql://<user>:<pw>@<host>:5432/<database>

metrics:
  metric1:
    type: gauge
    description: A sample gauge

queries:
  query1:
    interval: 5
    databases: [db1]
    metrics: [metric1]
    sql: SELECT random() AS metric1
```
(where I have filled in \<user\>, \<password\>, etc)

And here is the command I run

```
docker run -p 9560:9560/tcp -v "$PWD/config.yaml:/config.yaml" --rm -it adonato/query-exporter:latest -- /config.yaml
```

When I run the command to start the query exporter, I get no response, it just hangs.

**Comment by albertodonato** [comment]
Have you tried querying the `/metrics` endpoint?

By default no output is shown in the console unless there's an error. You can increase verbosity by adding `-L DEBUG` to the command line.

**Comment by stephenfrench9** [comment]
Ah Thank You! These remedies did the trick. I appreciate the boost

**Comment by albertodonato** [comment]
No problem

**Comment by stephenfrench9** [comment]
@albertodonato I am getting a nice distribution with a nice tail, just like I want:

```
# HELP metric2 A sample histogram
# TYPE metric2 histogram
metric2_bucket{database="db1",le="-50.0"} 0.0
metric2_bucket{database="db1",le="-49.0"} 0.0
metric2_bucket{database="db1",le="-48.0"} 0.0
metric2_bucket{database="db1",le="-47.0"} 3.0
metric2_bucket{database="db1",le="-46.0"} 3.0
metric2_bucket{database="db1",le="-45.0"} 3.0
metric2_bucket{database="db1",le="-44.0"} 3.0
metric2_bucket{database="db1",le="-43.0"} 3.0
metric2_bucket{database="db1",le="-42.0"} 3.0
metric2_bucket{database="db1",le="-41.0"} 6.0
metric2_bucket{database="db1",le="-40.0"} 15.0
metric2_bucket{database="db1",le="-39.0"} 15.0
metric2_bucket{database="db1",le="-38.0"} 30.0
metric2_bucket{database="db1",le="-37.0"} 33.0
metric2_bucket{database="db1",le="-36.0"} 33.0
metric2_bucket{database="db1",le="-35.0"} 39.0
metric2_bucket{database="db1",le="-34.0"} 39.0
```

So that is really satisfying.

But I have a question. Each time I run the query, I get the "full picture" so to say - meaning I don't want to remember what the results of the query were the last time around and then add onto them. Each single time the query runs, it produces the complete distribution, just how I want it. You could say that I have a time evolving distribution, and each query is a snapshot of that time evolution, and I just want to view the snapshots. But It appears all of my snapshots are getting added together. Is there a way to avoid this?

**Comment by stephenfrench9** [comment]
For reference, here is my config, and thank you again for all of the  help getting started, excited for  this tool.

```
metrics:
  metric2:
    type: histogram
    description: A sample histogram
    buckets: [-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

queries:
  query2:
    interval: 20
    databases: [db1]
    metrics: [metric2]
    sql: |
      select -TRUNC((extract(EPOCH from now()) - extract(EPOCH from work_start_date))/86400) as metric2
      from app_clinicalreport
      where status in ('variant_interpretation', 'report_writing', 'data_qc', 'ready_for_signature', 'dlo_review')
      AND TRUNC((extract(EPOCH from now()) - extract(EPOCH from work_start_date))/86400) < 50
```
