### ISSUE TITLE
Queries with parameters not updated correctly

### ISSUE THREAD

**Issue by invokermain** [albertodonato/query-exporter#57]
**Is your feature request related to a problem? Please describe.**
I assume this isn't supported at the moment. Currently when defining a single metric, then running multiple queries against said metric with unique labels only one metric is recorded/exposed to `/metric` endpoint.

For example with a config like such:
```
metrics: 
  my_gauge: 
    description: "..."
    labels: 
      - var_name
    type: gauge
queries: 
  query_1: 
    databases: 
      - db1
    interval: 1m
    metrics: [my_gauge]
    sql: |
        SELECT
                1 my_gauge
                , 'query_1' var_name
  query_2: 
    databases: 
      - db1
    interval: 1m
    metrics: [my_gauge]
    sql: |
        SELECT
                2 my_gauge
                , 'query_2' var_name
```

**Describe the solution you'd like**
I would expect this too show two rows on `/metrics` endpoint:

```
my_gauge{database="...",var_name="query_1"} 1.0
my_gauge{database="...",var_name="query_2"} 2.0
```

**Additional context**
The reason I think this is a good pattern is having more granular queries coupled with good error handling will make this query_exporter very robust. For example if your query polled various databases on your SQL server and one database was offline the whole query set would error. By supporting this pattern it would return the other results as expected + the inclusion of a metric like:

```
query_last_run_status_ok{database="db1",query="query_1"} 0
query_last_run_status_ok{database="db1",query="query_2"} 1
```

would allow for great exporter health visibility on prometheus side.
