### ISSUE TITLE
Error from database "devdb": 'AsyncioEngine' object has no attribute 'hide_parameters'

### ISSUE THREAD

**Issue by andy812** [albertodonato/query-exporter#62]
I use query-exporter with oracle database. My config:
```
databases:
  devdb:
    dsn: oracle://user:passvord@example.com:1521/devdb
    keep-connected: true

metrics:
  new_test_metric_oracle:
    type: gauge
    description: test metrics

queries:
  query1:
    interval: 1m
    databases: [primedb]
    metrics: [new_test_metric_oracle]
    sql: |
      select count(1) as new_test_metric_oracle from TCTDBS.ACQUIRERBILATERALS;
```
I added instantclient 19.8 in adonato/query-exporter:2.4.0 image according https://github.com/albertodonato/query-exporter/pull/60/commits/fb08e3104280320f9a821fe69f7fc4cfa6dd4083
Logs:
```
2020-09-14 12:04:45,647 - INFO - aiohttp.web - Listening on http://0.0.0.0:9560
2020-09-14 12:04:45,761 - ERROR - query-exporter - error from database "devdb": 'AsyncioEngine' object has no attribute 'hide_parameters'.
2020-09-14 12:04:45,762 - DEBUG - query-exporter - updating metric "database_errors" inc 1 {database="devdb"}
2020-09-14 12:04:45,841 - ERROR - query-exporter - error from database "devdb": 'AsyncioEngine' object has no attribute 'hide_parameters'.
2020-09-14 12:04:45,842 - DEBUG - query-exporter - updating metric "queries" inc 1 {database="devdb",status="error"}
```
Any ideas how to fix it?

**Comment by xuanyuanaosheng** [comment]
@andy812  I had the same problem. The new oracledb 19.6 has this problem. The oracledb  version 11.2.0.4 works fine.

**Comment by Teriand** [comment]
same problem today with default user right.
after add all right - work fine

I don't know exactly which rights from the list helped

```
-- Create the user 
create user CLEAR_LOG
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT
  quota unlimited on users;
-- Grant/Revoke role privileges 
grant connect to CLEAR_LOG;
-- Grant/Revoke system privileges 
grant alter any table to CLEAR_LOG;
grant create any index to CLEAR_LOG;
grant create database link to CLEAR_LOG;
grant create job to CLEAR_LOG;
grant create procedure to CLEAR_LOG;
grant create sequence to CLEAR_LOG;
grant create table to CLEAR_LOG;
grant debug connect session to CLEAR_LOG;
grant delete any table to CLEAR_LOG;
grant drop any index to CLEAR_LOG;
grant drop any table to CLEAR_LOG;
grant select any dictionary to CLEAR_LOG;
grant select any table to CLEAR_LOG;
```

**Comment by manartezekov** [comment]
connect to Oracle 19.* doesn't work? I had same problem with connect?

**Comment by searchgithub** [comment]
I have the same issue on "Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production"
ERROR - query-exporter - error from database "my_db": 'AsyncioEngine' object has no attribute 'hide_parameters' with "query-exporter 2.2.0"

But "1.4.0" is working fine.

**Comment by albertodonato** [comment]
Hi. I unfortunately don't have access to an oracle db to test.

Is there any way to setup a test server locally with docker?

**Comment by aorfanos** [comment]
Issue also exists in 'query-exporter:latest/2.5.0', connecting to MySQL 5.7.

I receive the following message:

```
2020-11-24 17:52:00,927 - ERROR - query-exporter - error from database "devtestdb": 'AsyncioEngine' object has no attribute 'hide_parameters'.
```

My `config.yaml` looks like:
```
databases:
    dsn: mysql://user:pass@host:port/testdb

metrics:
  sample_metric:
    type: gauge
    description: How many seconds have passed since update

queries:
  sample_metric:
    interval: 15
    databases: [testdb]
    metrics: [sample_metric]
    sql: SELECT UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(lastsent) AS sample_metric FROM randomtable ORDER BY lastsent DESC LIMIT 1
```
