### ISSUE TITLE
cx_Oracle.DatabaseError ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by andy812** [albertodonato/query-exporter#67]
**Describe the bug**

We've got config file with ~90 queries. quert-exporter works correctly after start, but then we've got cx_Oracle.DatabaseError ORA-01000: maximum open cursors exceeded. We tried to change keep-connected to "false", but it didn't fix the problem.

**Installation details**

Oracle Database 11g Enterprise Edition Release 11.2.0.4.0
query-exporter 2.4.0
instantclient 19.8

**Query example**
```
      query92:
        interval: 60s
        databases: [mydb]
        metrics: [payment_cnt_all_last_minute]
        sql: |
          SELECT pay as payment_cnt_all_last_minute
          FROM payment_cnt_all_last_minute    
```
**Log**
```
2020-10-26 11:34:50,912 - ERROR - query-exporter - query "query92" on database "mydb" failed: (cx_Oracle.DatabaseError) ORA-01000: maximum open cursors exceeded
[SQL: SELECT pay as payment_cnt_all_last_minute
FROM payment_cnt_all_last_minute]
(Background on this error at: http://sqlalche.me/e/4xp6)
```
Show info about cursors:
```
select a.value count_cur, s.program, s.username, s.sid, s.serial#
from v$sesstat a, v$statname b, v$session s
where a.statistic# = b.statistic#  and s.sid=a.sid
and b.name = 'opened cursors current' and program like '%query-exporter-%'
```
![изображение](https://user-images.githubusercontent.com/29895539/97282607-eb0e5480-184f-11eb-9ff7-ba51cf5ced58.png)
How can we fix this issue?
