### ISSUE TITLE
Query-exporter is duplicating data

### ISSUE THREAD

**Issue by PythonCoderAS** [albertodonato/query-exporter#86]
**Describe the bug**

I am running a query, and on Prometheus, the values of the query are increasing every fetch, even though I have confirmed that the values are constant via sqlite3 CLI tool.

**Installation details**

- operating system: Ubuntu 20.04
- query-exporter installation type:
  - docker image: latest

**To Reproduce**

If possible, please provide detailed steps to reproduce the behavior:

1. Config file content (redacted of secrets if needed)
2. 
```yml
databases:
        db1:
                dsn:
                        dialect: sqlite
                        database: <path>/database.db
                keep-connected: false


metrics:
        metric1:
                type: counter
                description: Messages sent by user in channel in guild
                labels: [guild, channel, author]

queries:
        query1:
                interval: 15
                databases: [db1]
                metrics: [metric1]
                sql: SELECT GUILD_ID AS guild, CHANNEL_ID as channel, AUTHOR_ID as author, NUM as metric1 FROM STAT
```

2. Ran query-exporter with the following command line: I did not add any CLI arguments.

3. Got the error when: I try to view results
