### ISSUE TITLE
Running service using docker composer results in such error: argument config: can't open '/config.yaml'

### ISSUE THREAD

**Issue by rompl1** [albertodonato/query-exporter#87]
Hi there,

Unable to run service as a container using docker-composer. Could you please help me out with this?
Config content of docker-compose.yml:

```
version: "3.7"

networks:
  barbora-monitor_network:

services:
  sqlquery_exporter:
    image: adonato/query-exporter
    ports:
      - "9560:9560"
    volumes:
      - ./sqlquery_exporter/:/etc/sqlquery_exporter/
    networks:
      - barbora-monitor_network
    depends_on:
      - prometheus
    restart: always
```

docker-compose up -d

docker logs --tail 50 --follow --timestamps barboramonitor_sqlquery_exporter_1

2021-06-21T07:16:00.480616300Z query-exporter: error: argument config: can't open '/config.yaml': [Errno 2] No such file or directory: '/config.yaml'
2021-06-21T07:16:01.643102100Z usage: query-exporter [-h] [-H HOST [HOST ...]] [-p PORT]
2021-06-21T07:16:01.643157600Z                       [-L {CRITICAL,ERROR,WARNING,INFO,DEBUG}]
2021-06-21T07:16:01.643167500Z                       [--process-stats] [-V] [--check-only]
2021-06-21T07:16:01.643171400Z                       config
2021-06-21T07:16:01.643174400Z query-exporter: error: argument config: can't open '/config.yaml': [Errno 2] No such file or directory: '/config.yaml'
