### ISSUE TITLE
Multi-rows results

### ISSUE THREAD

**Issue by m8t** [albertodonato/query-exporter#9]
It seems an output with multiple rows is not supported.

I have queries with a clause GROUP BY which provides results in multi-rows like this:

```
> SELECT column2,COUNT(*) AS value FROM table GROUP BY column2;
+---------+-------+
| column2 | value |
+---------+-------+
| Type1   |     4 |
| Type2   |    73 |
| Type3   |    38 |
+---------+-------+
```

It would be practical to support multi-rows results that provides this kind of metrics:

```
databases:
  dbname:
    dsn: driver://foo:bar@baz/dbname
metrics:
  dbname_metric_by_column2:
    description: Total values by column2
    type: gauge
queries:
  dbname_metric_by_column2:
    databases: [dbname]
    metrics: [dbname_metric_by_column2]
    sql: SELECT column2,COUNT(*) FROM table GROUP BY column2
```
```
dbname_metric_by_column2{label="Type1"} 4
dbname_metric_by_column2{label="Type2"} 73
dbname_metric_by_column2{label="Type3"} 38
```

What do you think?

**Comment by albertodonato** [comment]
Hi,

this is supported in 1.8.0 by declaring the metric with a label and using explicit column names in the query, something like:

```
metrics:
  dbname_metric_by_column2:
    description: Total values by column2
    type: gauge
    labels: [label]
queries:
  dbname_metric_by_column2:
    databases: [dbname]
    metrics: [dbname_metric_by_column2]
    sql: |
        SELECT column2 AS dbname_metric_by_column2, COUNT(*) AS label
        FROM table GROUP BY column2
```

(haven't tested the exact configuration, but that's the idea). Also see the readme for a similar example.
Note that column names (or aliases) need to match all declared metrics and their labels.

Let me know if this solves your issue
