### ISSUE TITLE
Clickhouse support or via clickhouse mysql compatability layer

### ISSUE THREAD

**Issue by ivlovric** [albertodonato/query-exporter#98]
Hi!

I am trying to use Clickhouse database as source for metrics. To be more precise, I am trying to use Clickhouse's MySQL compatible interface but without success.

This is dsn config that I used and also tried with 2 drivers options in dsn config. `dsn: mysql://`
I want to know how to connect to Clickhouse database over MySQL interface or is there any plan to support Clickhouse natively?

Error that I am getting is this:
`2021-12-14 16:43:59,935 - ERROR - query-exporter - error from database "db1": list index out of range`

I also verified that I can connect to Clickhouse MySQL interface with external database management tool
Any feedback or guide how I can use Clickhouse with this nice exporter is appreciated.

Thanks a lot,
I

**Comment by albertodonato** [comment]
Hi, I've never used Clickhouse, but from a quick search it seems there's a [sqlalchemy driver](https://pypi.org/project/clickhouse-sqlalchemy/) for it.

If you manually install query-exporter in a virtualenv and that additional driver, you should be able to specify `clickhouse://...` as a dsn to connect (as described in the driver doc).

**Comment by ivlovric** [comment]
Hi!
Thank you for quick reply. I already installed sqlalchemy driver but it was unclear to me how it can be used if it can be used at all here. Will try manually installing this exporter and report with results

**Comment by ivlovric** [comment]
Got it working with Sqlalchemy clickhouse driver and manual install. Thanks for support albertodonato. Now I have one more question but it is not strictly related to issue title. :) This exporter always expects only 1 query result?

**Comment by albertodonato** [comment]
Great! Good to know it works with Clickhouse too.

WRT your question, you can return multiple rows from a query, each metric value will be recorded (for instance if each row has different label values, they'll be recorded accordingly).

**Comment by gaoxingliang** [comment]
I build a docker image which supports clickhouse:
https://hub.docker.com/r/edwardg/query-exporter/tags

the dockerfile:
```
FROM adonato/query-exporter
RUN pip install clickhouse-sqlalchemy==0.0.10
```

and an example conf:
```yaml
databases:
  ch:
    dsn: clickhouse+native://user:pass@ip:9000/default
    labels:
      datasource: query_exporter    
metrics:
    entemployrelid_call_count:
        type: gauge
            
queries:
  entemployrelid_call_count:
    interval: 5m
    databases: [ch]
    metrics: [entemployrelid_call_count]
    sql: SELECT count(request.url) AS entemployrelid_call_count  FROM xxx;


```
