### ISSUE TITLE
Database starting by number is not allowed - REGEX

### ISSUE THREAD

**Issue by domino540** [albertodonato/query-exporter#99]
**Describe the bug**

When I have database with name starting by number - export will fail and can not be run. 

```
root@debian:~# /usr/local/bin/query-exporter /etc/prometheus-query/config.yml
Invalid config at databases: '8yqz3x' does not match any of the regexes: '^[a-zA-Z_:][a-zA-Z0-9_:]*$'
```

```
  8yuz3x:
    dsn: mysql://user:pass@192.168.0.1:3306/8yuz3x
    labels:
      customer: NOX TELECOM
      locality: AXC
```
